### ISSUE TITLE
HW09 ifelse issue

### ISSUE THREAD

**Issue by mtaylor-semo** [gabd-students/winingar_andrea#6]
Your code is correct when it runs the *first* time. It also runs correctly when you run it the second time but that is when the problem manifests. Look at the first part your code. I'm showing only the `ifelse` for sex but the you will see how the logic applies for the riffle ifelse, too.
```
darter_data <- darter_data %>% 
  mutate(sex = ifelse(sex == "f", 
                             "female", 
                             "male"), etc....
```
You are using `ifelse()` correctly. If sex is f, then it is assigned female, otherwise male. When you run the code the first time, you get the correct result. The `sex` column has either `female` or `male`. If you run the code again, the sex column no longer has any `f` values, so the `else` part runs, changing all `female` values to `male`. The same logic applies for riffles.  The first time matches `1` but the second time, there are no matches for `1`, just `riffle 1` and `riffle 2`.

The reason for this is that you are piping in `darter_data` and saving the result back to `darter_data`. The `sex` column now has the updated data. If you run the chunk again, the data no longer match like you expect.  Sometimes it is okay to overwrite an object with the new information (I do it all the time) but this is not one of those times. You could save it to a new object (like `wrangled_darters`) but I recommend a different method.

Go up to your import chunk.
```{r}
import_darter <- read_csv(here('data', 'darters.csv'))
darter_data <- import_darter %>% 
  filter(species == "blennioides" | species == "caeruleum" | species == "spectabile")
```
There's nothing wrong with your code above but you could simplify if by piping the imported data into your filter, like so.
```{r}
import_darter <- read_csv(here('data', 'darters.csv')) %>% 
  filter(species == "blennioides" | species == "caeruleum" | species == "spectabile")
```
Then, change your wrangling chunk to 
```{r}
darter_data <- import_darter %>% 
  mutate(sex = ifelse(sex == "f", 
                             "female", 
                             "male"), etc...
```
This keeps `import_darter` as "original" data in unmodified form.  You then pipe your original data into the wrangling code.  If you have to run your wrangling code again (e.g., while editing), you start from scratch so you don't accidentally overwrite your desired results.

**Comment by Andrearashay** [comment]
I got it fixed! Thanks!!
